version: '3'
services:
    mongo03:
        hostname: mongo03
        container_name: mongo03
        image: mongo
        ports:
            - 30003:27017
        restart: always
        entrypoint: [ '/usr/bin/mongod', '--bind_ip_all', '--replSet', 'my-mongo-set']

networks:
    default:
        external:
            name: my-mongo-cluster
