version: '3'
services:
    python-client:
        build: 
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./app:/usr/src/app
        ports:
            - 5000:5000
networks:
  default:
    external:
      name: shared