version: '3'
services:
    mongo02:
        hostname: mongo02
        container_name: mongo02
        image: mongo
        ports:
            - 30002:27017
        restart: always
        entrypoint: [ '/usr/bin/mongod', '--bind_ip_all', '--replSet', 'my-mongo-set']

networks:
    default:
        external:
            name: my-mongo-cluster
